heat_template_version: 2018-08-31

description: Template for creating Server Groups

parameters: #declares the parameters
  keypair:
    type: string
    default: <keypair>
    description: KeyPair to use to be able to SSH into instance
  image_id:
    type: string
    label: <image-name>
    default: <image-id>
    description: Image for the VM
  flavor_id:
    type: string
    label: <flavor-name>
    default: <flavor-id>
    description: Flavor for VM
  security_group_id:
    type: string
    default: <default-security-group-id>
    description: Default Security group

resources:

  affinity_group:
    type: OS::Nova::ServerGroup
    properties:
      name: hosts on separate compute nodes
      policies:
        - affinity

  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: flavor_id }
      key_name: {get_param: keypair }
      networks:
        - network: Internal #define the network to use as internal
      security_groups:
        - { get_param: security_group_id }
      user_data_format: RAW
      name: server_1
      scheduler_hints:
        group: {get_resource: affinity_group}
