name: CI - Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: ammaraskar/sphinx-action@master
          with:
            pre-build-command: python3 -m pip install -r requirements.txt
            docs-folder: '.'
